### ISSUE TITLE
Crusher e4s compilers.yaml bug

### ISSUE THREAD

**Issue by kwryankrattiger** [spack/spack-configs#48]
In the e4s spack.yaml for crusher, there is a `gcc@7.5.0` and a `gcc@7-os` system compiler option. This is great and very useful.

However, these compilers do not load the PrgEnv-gnu module and therefore all of the other system modules are not loaded correctly. As a result, `cray-libsci` will find the `PrgEnv-cray` version of `cray-libsci` rather the the GNU version. This makes all of the dependent packages fail to build with errors of a missing blas/lapack symbols because it cannot find the `cray-libsci` library because it is looking in the path of cray for the library name with gnu in it.

**Comment by shahzebsiddiqui** [comment]
@jfinney10 @mpbelhorn

**Comment by mpbelhorn** [comment]
@kwryankrattiger This isn't a bug; it is intentional. The compiler specs `gcc@7.5.0` and `gcc@7-os` both point to the OS-provided compiler in `/usr/bin` on the login nodes. On Crusher (running SLES 15.3) this is a GCC v7.5 toolchain. The compute nodes have sufficient runtime libraries to execute binaries build with the login node OS toolchain. But this toolchain is not part of the Cray Programming Environment (CPE) itself and cannot link against or use CPE-provided runtime libraries like libsci or cray-mpich.

We use this toolchain to build software targeting primarily the login nodes that are not performance-critical or optimized for the compute nodes but which users request. For example, text editors (vim, emacs), general purpose utilities (cmake, git, tmux, screen,etc..).

The distinction between the two compiler specs `gcc@7.5.0` vs `gcc@7-os` is that even though they both point to the same OS-provided toolchain, we expose public modulefiles for things built with `gcc@7.5.0` and use `gcc@7-OS` to build general-purpose utilities that cannot be built with CPE-provided toolchains but which are needed in mixed-compiler builds of software targeting the compute nodes and anything built with `gcc@7-os` is explicitly denied a public modulefile. We do not currently need or use the `gcc@7-os` compiler spec but we have it defined in our configs should it become necessary to use it. I suspect that after mixed-toolchain support is improved in spack's new clingo concretizer (perhaps in spack v0.19) we won't need this second alias.

If you're building software that's meant to link against Cray PE libraries and run on the compute nodes at maximum performance, use a Cray PE toolchain and target the Cray platform and not the SLES-provided generic GCC.
